"""initial migration

Revision ID: 889147137137
Revises: 
Create Date: 2025-11-08 14:06:04.530131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '889147137137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipm')
    op.drop_table('kemiskinan')
    op.drop_table('regions')
    with op.batch_alter_table('apbd', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('year',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index('fk_data_province')
        batch_op.drop_index('fk_data_regency')
        batch_op.create_index(batch_op.f('ix_data_province_id'), ['province_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_regency_id'), ['regency_id'], unique=False)
        batch_op.drop_constraint('data_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('regencies', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_regencies_province_id'), ['province_id'], unique=False)
        batch_op.drop_constraint('regencies_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'provinces', ['province_id'], ['id'])

    with op.batch_alter_table('stuntings', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stuntings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('year',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=False)

    with op.batch_alter_table('regencies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('regencies_ibfk_1', 'provinces', ['province_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_regencies_province_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('data_ibfk_1', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_data_regency_id'))
        batch_op.drop_index(batch_op.f('ix_data_province_id'))
        batch_op.create_index('fk_data_regency', ['regency_id'], unique=False)
        batch_op.create_index('fk_data_province', ['province_id'], unique=False)
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('apbd', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('kemiskinan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('tahun', mysql.YEAR(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='kemiskinan_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ipm',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tahun', mysql.YEAR(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='ipm_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('regions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
